default_model: "claude-sonnet-4-20250514"
execution_engine: "asyncio"
streaming: true

# Model providers
anthropic:
  api_key: ${ANTHROPIC_API_KEY}

openrouter:
  api_key: ${OPENROUTER_API_KEY}
  base_url: "https://openrouter.ai/api/v1"

# MCP servers - adjusted for production Docker environment
mcp:
  servers:
    energy-data:
      transport: "stdio"
      command: "python"  # Use python directly in Docker
      args: ["mcp-servers/energy-data/server.py"]
      env:
        PYTHONPATH: "/app"
        DEMO_MODE: ${DEMO_MODE:-false}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_SERVICE_KEY}
    
    calculation-engine:
      transport: "stdio"
      command: "python"
      args: ["mcp-servers/calculation-engine/server.py"]
      env:
        PYTHONPATH: "/app"
        DEMO_MODE: ${DEMO_MODE:-false}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_SERVICE_KEY}
    
    template-provider:
      transport: "stdio"
      command: "python"
      args: ["mcp-servers/template-provider/server.py"]
      env:
        PYTHONPATH: "/app"
        DEMO_MODE: ${DEMO_MODE:-false}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    
    supabase-storage:
      transport: "stdio"
      command: "python"
      args: ["mcp-servers/supabase-storage/server.py"]
      env:
        PYTHONPATH: "/app"
        DEMO_MODE: ${DEMO_MODE:-false}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
        BUCKET_NAME: ${BUCKET_NAME:-bespaarplan-reports}

# Logging configuration for production
logger:
  type: "console"  # Use console output for cloud logging
  level: "info"
  progress_display: false  # Disable progress bars in production
  show_chat: false  # Reduce log verbosity
  show_tools: true  # Keep tool calls visible for debugging
  truncate_tools: true
  enable_markup: false  # Disable rich markup for cleaner logs