default_model: "claude-sonnet-4-20250514"
execution_engine: "asyncio"
streaming: true

# Model providers
anthropic:
  api_key: ${ANTHROPIC_API_KEY}

openrouter:
  api_key: ${OPENROUTER_API_KEY}
  base_url: "https://openrouter.ai/api/v1"

# Model configurations should be set in code via RequestParams, not here

# MCP servers - using existing working servers
mcp:
  servers:
    energy-data:
      transport: "stdio"
      command: "uv"
      args: ["run", "python", "mcp-servers/energy-data/server.py"]
      env:
        DEMO_MODE: "false"
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
    
    calculation-engine:
      transport: "stdio"
      command: "uv" 
      args: ["run", "python", "mcp-servers/calculation-engine/server.py"]
      env:
        DEMO_MODE: "false"
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
    
    template-provider:
      transport: "stdio"
      command: "uv"
      args: ["run", "python", "mcp-servers/template-provider/server.py"]
      env:
        DEMO_MODE: "false"
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
        SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
        BUCKET_NAME: ${BUCKET_NAME:-bespaarplan-reports}
    
    supabase-storage:
      transport: "stdio"
      command: "uv"
      args: ["run", "python", "mcp-servers/supabase-storage/server.py"]
      env:
        DEMO_MODE: "false"
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
        BUCKET_NAME: ${BUCKET_NAME:-bespaarplan-reports}

# Logging configuration
logger:
  type: "file"
  level: "info"
  path: "logs/fastagent.jsonl"